### ISSUE TITLE
Allow to configure colors

### ISSUE THREAD

**Issue by shpoont** [awslabs/aws-shell#100]
aws-shell is not compatible with themed terminals, e.g. solarized light, it would be nice to be able to configure colors in some way.

**Comment by donnemartin** [comment]
@shpoont I think you might be referring to the syntax highlighter/lexer.  If so, you can update your theme (or disable it) by changing the following value in `~/.aws/shell/awsshellrc`:

```
# visual theme. possible values: manni, igor, xcode, vim,
# autumn,vs, rrt, native, perldoc, borland, tango, emacs,
# friendly, monokai, paraiso-dark, colorful, murphy, bw,
# pastie, paraiso-light, trac, default, fruity.
# to disable themes, set theme = none
theme = vim
```

@jamesls do you think it might be helpful to include a dot command to change the theme?  Maybe something like `.theme`?

**Comment by shpoont** [comment]
@donnemartin you are right! I couldn't find it in docs so I assumed it didn't exist. Thanks!
