### ISSUE TITLE
OSError: [Errno 1] Operation not permitted:

### ISSUE THREAD

**Issue by keithyau** [awslabs/aws-shell#101]
Hi there, I tried both command on my mac with the same error. i used sudo, but it is still operation not permitted. Any idea? thanks your help !

sudo pip install aws-shell --upgrade --ignore-installed six

sudo pip install aws-shell

![image](https://cloud.githubusercontent.com/assets/659311/12107884/b5dc87b8-b3ab-11e5-94f7-47de8be364b4.png)

**Comment by jamesls** [comment]
Are you on El Capitan?  This is a known issue on El Capitan, but I'm surprised you're still getting this error even when you run `--ignore-installed six`.  Can you confirm a few things for me?

1. What version of Mac OS X are you running?
2. Can you share the whole output of `sudo pip install aws-shell --upgrade --ignore-installed six`?
