### ISSUE TITLE
Sort sub commands alphabetically

### ISSUE THREAD

**Issue by jtblin** [awslabs/aws-shell#110]
Sub commands are not sorted alphabetically during autocomplete which makes it hard to find the right one e.g.:

![image](https://cloud.githubusercontent.com/assets/1388974/12700194/9546c01e-c82c-11e5-9868-722a0d35ca92.png)

**Comment by donnemartin** [comment]
I think this is related to #5: Fix fuzzy search algorithm

Although you lose fuzzy searching, the `F2` key toggles between fuzzy and substring matching.  Substring matching should sort alphabetically.

**Comment by jamesls** [comment]
I agree, this is the same issue for #5.  Your option right now is to use substring matching if you want sorting alphabetically (F2 to toggle as Donne mentioned).  Let's track the remaining work for fixing fuzzy searching over in #5.
