### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Fale** [awslabs/aws-shell#123]
Hi,
Last released version is 6 months old and big improvements have been done since that moment in the master version. Would it be possible to make a new release with those changes?

**Comment by jamesls** [comment]
The latest release [0.1.1](https://pypi.python.org/pypi/aws-shell/0.1.1) was released 5/21/16.  What version are you using?

**Comment by Fale** [comment]
v0.1.0 that is the last tagged on github. Thanks for letting me know that the version 0.1.1 has been released :)

**Comment by jamesls** [comment]
Ah.  Thanks for pointing that out, I didn't tag the 0.1.1 release on github.  I'll get that fixed.
