### ISSUE TITLE
Missing python-wheel installation dependency

### ISSUE THREAD

**Issue by hackel** [awslabs/aws-shell#124]
I attempted to install aws-shell (on Ubuntu 16.04), and got a bunch of errors: `invalid command 'bdist_wheel'`.  Installing python-wheel resolved them.  This should be added to the documentation at least, if not explicitly added as a dependency.

**Comment by jamesls** [comment]
What version of pip are you using?

We don't upload any .whl files for the `aws-shell`, so I'm not sure why this error is occurring.  As far as I know we shouldn't have a dependency on wheels.

**Comment by hackel** [comment]
This was using the Ubuntu python-pip 8.1.1-2ubuntu0.1 package.  [Here](https://github.com/awslabs/aws-shell/files/315018/install-aws-shell.txt) is the console output when I try to install.

If I manually upgrade to pip 8.1.2 and install with --user, I don't seem to have this problem.
