### ISSUE TITLE
Can you please share a document to install AWS shell on windows

### ISSUE THREAD

**Issue by rongalav** [awslabs/aws-shell#140]

**Comment by rongalav** [comment]
I downlaoded the github package and ran setup.py --install..
after that nothing happened
had python 3.6.X

**Comment by rongalav** [comment]
I tried with python 2.7.x..no Luck. Any update on how to get it worked on Windows 7?

**Comment by donnemartin** [comment]
Hi @rongalav, sorry I didn't get to respond to this sooner.

Are the instructions in the [Installation](https://github.com/awslabs/aws-shell#installation) section not working for your system?

     pip install aws-shell

You'll need to download/install Python if you don't already have it:

https://www.python.org/downloads/windows/

If you don't have pip, check out the following link for install instructions:

http://stackoverflow.com/questions/4750806/how-do-i-install-pip-on-windows
