### ISSUE TITLE
TypeError:generate shorthand example() got an unexpected keyword argument 'cli argument'

### ISSUE THREAD

**Issue by wenwenxiong** [awslabs/aws-shell#154]
generate shorthand example() got an unexpected keyword argument 'cli argument'

**Comment by donnemartin** [comment]
Hi @wenwenxiong, I'm not seeing this error on a fresh install on OS X 10.10 with Python 3.5.  Can you provide more details about your OS and Python version?

What is the output of the following?

     $ pip freeze

Can you post the full exception traceback?

Can you try installing in a [virtualenv](http://docs.python-guide.org/en/latest/dev/virtualenvs/)?
