### ISSUE TITLE
Unable to scroll documentation pane

### ISSUE THREAD

**Issue by mmautner** [awslabs/aws-shell#159]
How do I scroll the help documentation pane in the bottom half of my `aws-shell`?

I'm happy to add the answer to the README, but not sure how to do it myself.

<img width="1385" alt="screenshot 2016-10-22 13 45 30" src="https://cloud.githubusercontent.com/assets/1419652/19622411/e65a1e18-985d-11e6-8d97-3b72cf4ba325.png">

**Comment by donnemartin** [comment]
Hi @mmautner, I don't think this is possible at the moment.

**Comment by mmautner** [comment]
Thanks @donnemartin -- I figure the answer lies somewhere in [`prompt-toolkit`'s docs](https://github.com/jonathanslenders/python-prompt-toolkit).

Here is the window containing the docs from the awscli:

https://github.com/awslabs/aws-shell/blob/ab5ed9ae6f397d5ba98fd274716af265ababb468/awsshell/ui.py#L179-L186

**Comment by so0k** [comment]
Facing the same issue - saws actually opens the documentation link in the browser, which I'd prefer if window scrolling isn't possible

**Comment by statwonk** [comment]
Is it possible in emacs mode? Looking for the same functionality. @JordonPhillips I think making `aws-shell` comfortable for developers would really help the bottom line. Most expert developers I know still use a fairly even mix of web console / cli. Moving faster means more consumption. :)

**Comment by briantully** [comment]
aha! I thought I was going crazy and spend close to an hour trying to figure out why I couldn't focus on the documentation pane and scroll it. The last line visible in the documentation pane was "AVAILABLE COMMANDS" and without a way of scrolling to see the actual commands, I feel this pane does more harm than good?

**Comment by joguSD** [comment]
Ability to focus the documentation pane to navigate it as well as use the scroll wheel have been added in https://github.com/awslabs/aws-shell/pull/138
