### ISSUE TITLE
Future of aws-shell

### ISSUE THREAD

**Issue by stevepotayteo** [awslabs/aws-shell#160]
Hi,

Just checking back on this project. Was wondering what is the future of this project with regards to SAWS, and which project will be moving forward to be active developed as the 'de-facto' aws shell.

**Comment by donnemartin** [comment]
Hi @stevepotayteo, new feature development will be done on aws-shell.  Here are some additional details:

https://github.com/donnemartin/saws/issues/68#issuecomment-240067034

**Comment by stevepotayteo** [comment]
Thanks @donnemartin. Was wondering as I wanted to integrate either SAWS or aws-shell into my toolchain depending on active development. Thanks for your amazing work!

**Comment by donnemartin** [comment]
Thank you!
