### ISSUE TITLE
An error occured when create redshift cluster snapshot

### ISSUE THREAD

**Issue by jingjingnfp** [awslabs/aws-shell#175]
I installed aws cli on my local machine and try to write a command to mannually create a redshift cluster snapshot. I ran the command :
 +"aws redshift create-cluster-snapshot --cluster-identifier xxx --snapshot-identifier myfirstsnapshot"
 +I kept getting this error: "An error occurred (InvalidClientTokenId) when calling the CreateClusterSnapshot operation: The security token included in the request is invalid."
 +
 +I don't know why and couldn't find any solution.

**Comment by joguSD** [comment]
Have you run `aws configure`? 
Are you certain that the security token you're providing is still valid?
