### ISSUE TITLE
XDG Base Dir compatability

### ISSUE THREAD

**Issue by z0rc** [awslabs/aws-shell#191]
I understand that it's convenient and kinda awscli legacy approach to store everything in `~/.aws` on Linux.

Still nothing blocks this CLI utility to properly use `$XDG_CONFIG_HOME` path for configuration storage and `$XDG_CACHE_HOME` for cache.

To make it clear XDG base dir spec is already used by multitude of other CLI utilities, like git, systemd, mc, htop and many many others. Please keep our homes clean.

**Comment by joguSD** [comment]
This would need to happen upstream in the CLI. There's a feature request there for it already: https://github.com/aws/aws-cli/issues/2433. Closing in favor of that issue.
