### ISSUE TITLE
Add toolbar menu to easily toggle between options

### ISSUE THREAD

**Issue by donnemartin** [awslabs/aws-shell#26]
# Toolbar Options

* `F2` toggles fuzzy completions
* `F3` toggles `Vi` and `Emacs` key bindings
* `F4` toggles single and multiple columns in the autocompletion menu
* `F5` toggles the help pane
* `F10` exits `aws-shell`

## Fuzzy Toggle

Some users might want to turn off fuzzy matching.  I sometimes toggle this depending on what I'm doing.

On a related note, I think the current fuzzy matching works pretty well, although in some cases it actually results in more keystrokes (https://github.com/awslabs/aws-shell/issues/5).  For example:

     aws> ec2 describe-inst

### Fuzzy On

![Imgur](http://i.imgur.com/9hPh0Xu.png)

### Fuzzy Off

![Imgur](http://i.imgur.com/RuQO97W.png)

## Vi/Emacs Key Bindings

Currently `aws-shell` runs with `Vi`bindings, which might not suit everyone.  For `SAWS` and `aws-shell` personally I'm starting to use the `Emacs` mode more it feels more natural to me thinking of these apps as a command line tool rather than an editor.

TODO: With `Vi` bindings we might want to add info to let the user know what mode is active.

![Imgur](http://i.imgur.com/7omThRF.png)

![Imgur](http://i.imgur.com/XsazCGg.png)

## Single vs Multi Column Completion Menus

Some users might prefer the current multi column and others might prefer the single column.  I prefer the latter it seems 'less busy' and more like what I'm accustomed to with other apps, although it could take some scrolling unlike the multi column option where you see pretty much everything.

`prompt-toolkit` also handles the `meta` info differently single vs multi.  For single you see more `meta` right away, for multi, you only see `meta` for the currently highlighted completion.  I've also applied `pygments` styles to the menu and `meta`, although the multi `meta` style doesn't seem to be taking hold.

### Single Column

![Imgur](http://i.imgur.com/pXuYdz7.png)

### Multi Column

![Imgur](http://i.imgur.com/Qq498Vy.png)

### Single Column Meta

![Imgur](http://i.imgur.com/RycEm8Z.png)

### Multi Column Meta

![Imgur](http://i.imgur.com/jO2Xpde.png)

## Help Toggle

The help pane is really cool, although it does take up a lot of space.  Users might not always want to see this menu--for example they might only want to see this for unfamiliar commands.  Users  might want to reclaim that screen real estate.

### Menu On

![Imgur](http://i.imgur.com/5QaeQWj.png)

### Menu Off

![Imgur](http://i.imgur.com/g0HDDoD.png)

## Exit

To exit, `Ctrl-D` might not be obvious to some users.

![Imgur](http://i.imgur.com/LyhDO4R.png)

## TODO

These options should probably go to a config file to save their state between sessions.  

We could also make the toolbar content configurable if the number of options starts growing large.

**Comment by jamesls** [comment]
I believe this can be closed now, merged in https://github.com/awslabs/aws-shell/commit/654c93a3aa38c9344624f94922a4c1a928f201d7
