### ISSUE TITLE
Add auto suggest completions (fish-style) to more easily execute popular/recent commands

### ISSUE THREAD

**Issue by donnemartin** [awslabs/aws-shell#28]
## Suggest

![Imgur](http://i.imgur.com/vrPV3zl.png)

## Complete Suggestion

You can use the `right arrow key` to complete a suggestion.

![Imgur](http://i.imgur.com/tICvO5a.png)

## TODO 

This could also be a toolbar option.

For suggestions to be more effective I think we'd need to use a `FileHistory` instead of an `InMemoryHistory` which is persisted between sessions.  Another option is to hook up to something more general like  `.bash_history`.

We might need special handling for the `.edit` command if we switch to `FileHistory` as that could load a ton of history--maybe on `aws-shell` startup we can tag where we are in the history and only load from that checkpoint.

**Comment by jamesls** [comment]
Closing, this was merged via https://github.com/awslabs/aws-shell/commit/02ea3b58a221b6b72ac025e6f12990626689ca2c
