### ISSUE TITLE
Maintain history between sessions

### ISSUE THREAD

**Issue by donnemartin** [awslabs/aws-shell#29]
I think losing my command history after closing a session is inconvenient.  It's handy to be able to use the up arrow to cycle through previous commands.

With the new [auto suggestions](https://github.com/awslabs/aws-shell/issues/28), this becomes more prevalent.  For suggestions to be more effective I think we'd need to use a `FileHistory` instead of an `InMemoryHistory` which is persisted between sessions. Another option is to hook up to something more general like `.bash_history`.

We might need special handling for the `.edit` command if we switch to `FileHistory` as that could load a ton of history--maybe on `aws-shell` startup we can tag where we are in the history and only load from that checkpoint.

**Comment by jamesls** [comment]
Merged via https://github.com/awslabs/aws-shell/commit/f85805e916bbdba051cf8ce60c44ea11bc0fbc6e
