### ISSUE TITLE
Add aws-shell to awesome-aws

### ISSUE THREAD

**Issue by donnemartin** [awslabs/aws-shell#58]
# [Awesome AWS](https://github.com/donnemartin/awesome-aws) [![Awesome](https://cdn.rawgit.com/sindresorhus/awesome/d7305f38d29fed78fa85652e3a63e154dd8e8829/media/badge.svg)](https://github.com/sindresorhus/awesome)

A curated list of awesome AWS libraries, open source repos, guides, blogs, and other resources.

## The Fiery Meter of AWSome

* Repo with 0100+ Stars: :fire:
* Repo with 0200+ Stars: :fire::fire:
* Repo with 0500+ Stars: :fire::fire::fire:
* Repo with 1000+ Stars: :fire::fire::fire::fire:
* Repo with 2000+ Stars: :fire::fire::fire::fire::fire:

**Comment by jamesls** [comment]
:+1:

**Comment by donnemartin** [comment]
Added with https://github.com/donnemartin/awesome-aws/commit/7f37590f792dd4755ac2bdc4fda85e2f7b6a560f.
