### ISSUE TITLE
Clean up merged/closed branches?

### ISSUE THREAD

**Issue by donnemartin** [awslabs/aws-shell#63]
We have a good number of branches, most of which have been merged/closed.  Should we clean these up after they are merged?

**Comment by jamesls** [comment]
Yep, we should get those cleaned up.  I'll do a pass through them.

**Comment by donnemartin** [comment]
Sounds good, I just cleaned up mine.

**Comment by jamesls** [comment]
Mine as well.  I believe this can be closed now.
