### ISSUE TITLE
F3 shortcut becomes unresponsive after several keypresses.

### ISSUE THREAD

**Issue by donnemartin** [awslabs/aws-shell#70]
>e1ven
>
>After pressing f3 a few times to switch from emacs to vi and back, it got lost, and stopped responding to the command.

[Reddit Source](https://www.reddit.com/r/sysadmin/comments/3x2wns/awsshell_the_official_supercharged_aws_cli/cy14fyu)

**Comment by donnemartin** [comment]
I tried this just now, typing/toggling/repeat, not able to reproduce.

**Comment by e1ven** [comment]
I can't duplicate this anymore either. :/
It must have been something local to my system, perhaps some OSX equivalent of Sticky Keys.
I'd recommend closing, you can always re-open if someone else reports.

**Comment by jamesls** [comment]
Sounds good.  Let us know if you see this issue again.
