### ISSUE TITLE
How do I navigate the documentation panel?

### ISSUE THREAD

**Issue by pedros007** [awslabs/aws-shell#74]
When I type `ec2 run-instances`, I get the documentation panel on the bottom of the screen, as pictured here: 
![documentation-panel](https://cloud.githubusercontent.com/assets/368057/11823320/36ae9b04-a328-11e5-9661-81abfc0afe5a.png)

How do I scroll/page up/down in the documentation panel?  Default Emacs binding for `scroll-other-window` (`C-M-v`) and `scroll-other-window-down` (`C-M-S-v`) are not working for me.

**Comment by DanyC97** [comment]
interested too in this ...

**Comment by donnemartin** [comment]
Seems related to https://github.com/awslabs/aws-shell/issues/69.

**Comment by AnthonyWC** [comment]
+1 Really need an answer or fix.

**Comment by tchia04** [comment]
+1 Really need an answer or fix.

**Comment by joguSD** [comment]
Ability to focus the documentation pane to navigate it as well as use the scroll wheel have been added in https://github.com/awslabs/aws-shell/pull/138
