### ISSUE TITLE
COC?

### ISSUE THREAD

**Issue by alison985** [awslabs/aws-shell#82]
Hi,

I'm just wondering what your code of conduct is for this project?

Thanks,
Alison

**Comment by jamesls** [comment]
Hi Alison,
 
Amazon's code of conduct for employees may be found here: 
[http://phx.corporate-ir.net/phoenix.zhtml?c=97664&p=irol-govConduct​](http://phx.corporate-ir.net/phoenix.zhtml?c=97664&p=irol-govConduct) - this includes any employee activity on this project.
