### ISSUE TITLE
support for multiple profiles

### ISSUE THREAD

**Issue by umang1912** [awslabs/aws-shell#89]
I use multiple aws accounts, and aws credentials file has good support for profiles with separate keys. Would be good to have here.

**Comment by docent-net** [comment]
Same here; would be nice to be able to provide "--profile" param or to switch between accounts within ui

**Comment by elloboblanco** [comment]
Third vote!

**Comment by miked63017** [comment]
This would also be really useful if it had some sort of saml procedures built in, that would automatically select the new saml profile.

**Comment by donnemartin** [comment]
Thanks for the feedback everyone!

More discussion at https://github.com/awslabs/aws-shell/issues/9

**Comment by jamesls** [comment]
Working on it.

**Comment by jamesls** [comment]
Implemented via https://github.com/awslabs/aws-shell/pull/92
